#ifndef RTMPSERVER_RTMPENUMS_H
#define RTMPSERVER_RTMPENUMS_H

enum class BASIC_HEADER_TYPE{
    ONE_BYTE_HEADER,
    TWO_BYTE_HEADER,
    THREE_BYTE_HEADER
};
enum class MESSAGE_HEADER_TYPE{
    UNDEFINED,
    TYPE0,
    TYPE1,
    TYPE2,
    TYPE3
};

#endif //RTMPSERVER_RTMPENUMS_H
